import App from "../App/App";
import { SellerLogin } from "../Components/Forms/Seller/Login/SellerLogin";
import {
  Profile,
  Checkout,
  FlipkartPlus,
  Orders,
  Wishlist,
  Rewards,
  GiftCard,
  Register,
  Payment,
  AddAddress,
  Addresses,
  Product_Description,
  PageNotFound,
} from "../Pages";
import {
  Admin,
  User_list,
  Seller_list,
  Product_List,
  Add_Product,
  Stats,
} from "../Admin_Dashboard/Pages";
export const publicRoutes = [
  { path: "/register", Component: Register },
  { path: "/", Component: App },
  { path: "/productDescription", Component: Product_Description },
  { path: "/sellerLogin", Component: SellerLogin },
  { path: "*", Component: PageNotFound },
];
export const privateRoutes = [
  { path: "/profile", Component: Profile },
  { path: "/plus", Component: FlipkartPlus },
  { path: "/wishlist", Component: Wishlist },
  { path: "/rewards", Component: Rewards },
  { path: "/giftcard", Component: GiftCard },
  { path: "/orders", Component: Orders },
  { path: "/allAddresses", Component: Addresses },
  { path: "/address", Component: AddAddress },
  { path: "/checkout", Component: Checkout },
  { path: "/payment", Component: Payment },
  { path: "/admin", Component: Admin },
  { path: "/sellerList", Component: Seller_list },
  { path: "/userList", Component: User_list },
  { path: "/productList", Component: Product_List },
  { path: "/addProduct", Component: Add_Product },
  { path: "/stats", Component: Stats },
];
// export const routes = [
//     { path: "/profile", element: <Profile /> },
//     { path: "/plus", element: <FlipkartPlus /> },
//     { path: "/wishlist", element: <Wishlist /> },
//     { path: "/rewards", element: <Rewards /> },
//     { path: "/giftcard", element: <GiftCard /> },
//     { path: "/orders", element: <Orders /> },
//     { path: "/register", element: <Register /> },
//     { path: "/", element: <App /> },
//     { path: "/allAddresses", element: <Addresses /> },
//     { path: "/address", element: <AddAddress /> },
//     { path: "/productDescription", element: <Product_Description /> },
//     { path: "/checkout", element: <Checkout /> },
//     { path: "/payment", element: <Payment /> },
//     { path: "/sellerLogin", element: <SellerLogin /> },
//     { path: "/admin", element: <Admin /> },
//     { path: "/sellerList", element: <Seller_list /> },
//     { path: "/userList", element: <User_list /> },
//     { path: "/productList", element: <Product_List /> },
//     { path: "/addProduct", element: <Add_Product /> },
//     { path: "/stats", element: <Stats /> },
//   ];
